if(GetRealmName() ~= "Jin'do") then
return
end

STOP_Database = {
["Discørdkitty"]="1符文DK,1冰DK,1血DK",
["Meta"]="1平衡德",
["Erolok"]="1恢复德",
["Inimin"]="1射击猎,1生存猎,4生存猎",
["Nazmage"]="1奥法,1火法",
["Ryvaria"]="1奶骑,2奶骑",
["Cumx"]="1防骑,2审判骑",
["Multitask"]="1惩戒骑,2惩戒骑",
["Xárrion"]="1戒律牧",
["Aelyz"]="1暗牧,2暗牧",
["Shinuky"]="1奇袭贼",
["Ryvera"]="1恢复萨,1增强萨,2增强萨,3增强萨",
["Eurobeat"]="1痛苦术",
["Smirk"]="1恶魔术,3恶魔术",
["Abz"]="1毁灭术",
["Fêng"]="1武器战,3狂暴战,4狂暴战",
["Azizz"]="1狂暴战",
["Noxul"]="1邪DK,2冰DK",
["Deadlyrules"]="2邪DK",
["Reludruid"]="2平衡德",
["Gayirl"]="1典狱长德,2猫德",
["Davidbowy"]="2射击猎,3生存猎",
["Rryny"]="2火法,3奥法",
["Dorath"]="1审判骑,2防骑",
["Pwshield"]="2戒律牧",
["Okuurin"]="1战斗贼,2奇袭贼",
["Kyzisham"]="2元素萨",
["Sharuka"]="1元素萨,2恢复萨",
["Kazuko"]="2痛苦术",
["Salemdotter"]="2恶魔术",
["Majkuamk"]="2狂暴战",
["Grishnakh"]="3邪DK",
["Barbiegirl"]="3平衡德",
["Jhin"]="2生存猎,3射击猎",
["Aixen"]="3奶骑",
["Animaeus"]="3惩戒骑",
["Hessonite"]="3戒律牧",
["Heynp"]="1神牧,3暗牧",
["Ozylockbourn"]="2毁灭术,3痛苦术",
["Amoo"]="1猫德,2典狱长德,4平衡德",
["Freezyy"]="4奥法",
["Suicyde"]="2奥法,4火法",
["Deeppurple"]="4痛苦术",
["Pirujina"]="4恶魔术",
["Freshsucks"]="5生存猎",
["Clownmage"]="3火法,5奥法",
}

WP_Database = {
["LASTUPDATE"]="2023-11-02"
}
