if(GetRealmName() ~= "Jin'do") then
return
end

STOP_Database = {
["Discørdkitty"]="1符文DK,1血DK,2冰DK",
["Noxul"]="1冰DK",
["Deadlyrules"]="1邪DK",
["Reludruid"]="1平衡德",
["Erolok"]="1恢复德",
["Vibexo"]="1生存猎",
["Nazmage"]="1奥法,1火法",
["Odoac"]="1奶骑",
["Clueless"]="1审判骑,2防骑",
["Cumx"]="1防骑",
["Holybread"]="1惩戒骑",
["Pwshield"]="1戒律牧",
["Shinuky"]="1奇袭贼",
["Sharuka"]="1恢复萨,1元素萨",
["Enhancements"]="1增强萨",
["Abz"]="1毁灭术,1恶魔术",
["Fêng"]="1狂暴战,1武器战",
["Bujo"]="2邪DK",
["Meta"]="2平衡德",
["Gayirl"]="1典狱长德,2猫德",
["Davidbowy"]="2射击猎,3生存猎",
["Rryny"]="2火法,3奥法",
["Ryvaria"]="2奶骑",
["Multitask"]="2惩戒骑",
["Heynp"]="1暗牧,1神牧,2戒律牧",
["Aelyz"]="2暗牧",
["Okuurin"]="1战斗贼,2奇袭贼",
["Kyzisham"]="2恢复萨,2元素萨",
["Kazuko"]="2痛苦术",
["Salemdotter"]="2恶魔术",
["Ozylockbourn"]="1痛苦术,2毁灭术",
["Grishnakh"]="3邪DK",
["Barbiegirl"]="3平衡德",
["Jhin"]="2生存猎,3射击猎",
["Aixen"]="3奶骑",
["Animaeus"]="3惩戒骑",
["Hessonite"]="3戒律牧",
["Velbeth"]="3暗牧",
["Smirk"]="3恶魔术",
["Amoo"]="1猫德,2典狱长德,4平衡德",
["Inimin"]="1射击猎,4生存猎",
["Freezyy"]="4奥法",
["Suicyde"]="2奥法,4火法",
["Deeppurple"]="4痛苦术",
["Pirujina"]="3痛苦术,4恶魔术",
["Freshsucks"]="5生存猎",
["Clownmage"]="3火法,5奥法",
}

WP_Database = {
["Okuurin"]="ED:(战斗)7413/76.8%LV:(奇袭)1079/97.1%|0",
["LASTUPDATE"]="2023-05-28"
}
